### ISSUE TITLE
submit a PR

### ISSUE THREAD

**Issue by bbelderbos** [abaddonpuff/bladeART#1]
I see you have a branch with scripts, nice. Can you submit a pull request for my review?

Thanks
Bob

**Comment by abaddonpuff** [comment]
Not sure if I completed this or something yet missing xD

**Comment by bbelderbos** [comment]
I reviewed the commit, you mentioned a git cli auth issue, but you did manage to push code, so what prevented you from opening a PR?

Given all is on main now, you can start next effort on a new branch:

```
git checkout -b new-branch
# do work
git add .
git push origin new-branch
# open pr
```

**Comment by abaddonpuff** [comment]
I installed git on my terminal, so I did a git add for the entire blade/ folder. Which worked, then I did the git commit and asked me for my github username. Which I did, I put my password but then it failed the authentication. When I trieed again to add, I couldn't add the blade/ directory anymore but also when I did git status, it was not showing anything on staging. No idea what happened there.

**Comment by abaddonpuff** [comment]
OK Now it works, I needed a token :/ not username+password.

**Comment by bbelderbos** [comment]
A token? Normally you make an ssh key and add it to GitHub to authenticate without password when pushing to / pulling from GitHub. 
What about the files not shown up for staging? Has that been resolved too?

**Comment by bbelderbos** [comment]
If so we an close this out because the PR (as per issue title) worked fine last time and I could review.

**Comment by abaddonpuff** [comment]
Got it resolved when using SSH Thank you! The issue from staging has been resolved too

**Comment by bbelderbos** [comment]
great progress so far, note down one or more wins. I will further play with your code and give you some more guidance tomorrow on csv uploads in django ...
keep going!
