### ISSUE TITLE
learning Django / first view

### ISSUE THREAD

**Issue by bbelderbos** [abaddonpuff/bladeART#2]
As per Circle: recommended double PDM code clinic session by Antonio Melé, author of the excellent Django by Example book:

- part I: https://pybites.circle.so/c/pybites-coaching-calls/sections/117462/lessons/394744
- part II: https://pybites.circle.so/c/pybites-coaching-calls/sections/117462/lessons/394742

Part II might not be needed yet, let me know if part I is sufficient to already make the Django project structure and first view. The idea is to then try to make uploading a csv with emails possible through that view, and then call your scripts to process them.

**Comment by abaddonpuff** [comment]
I had some issues when using git cli on the authentication side and suddenly I couldn't add files anymore, so uploaded some progress through Github but forgot to upload on a branch accidentally pushed to main.

**Comment by bbelderbos** [comment]
OK I will review, but what was the issue exactly? Any errors for me to look at to help you?

**Comment by abaddonpuff** [comment]
Oh, the error was first. I tried to not create the models and going straight to the views. But was not working out. And then when I created the model for what I wanted to process from the CSV. I encountered this issue while testing inserting on the DB. Then I realized I was trying to display the userId which was a BigInteger while I was trying to return a string.

```
`Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/0xabaddon/repos/bladeART/.venv/lib/python3.10/site-packages/django/db/models/base.py", line 586, in __repr__
    return "<%s: %s>" % (self.__class__.__name__, self)
TypeError: __str__ returned non-string (type int)`
```

**Comment by bbelderbos** [comment]
OK but that's solved now right?

**Comment by bbelderbos** [comment]
So were you able to make your first view? 
Then we can move on to #3

**Comment by abaddonpuff** [comment]
Was able to do the first view. Just commited.
