### ISSUE TITLE
scripts design

### ISSUE THREAD

**Issue by bbelderbos** [abaddonpuff/bladeART#5]
@abaddonpuff please explain briefly here how the functions interrelate, how do you plan on calling them when a csv file gets uploaded?

I will review the code tomorrow ...

cheers
Bob

**Comment by abaddonpuff** [comment]
Functions:

employee2github: Process a list of employees and obtains a dictionary based to their associated github account
(Input: CSV of employees or text file)

transformDict2CSV: Transforms a dictionary of employees and provides a CSV, for readibility and sharing (input: employee2github output: CSV)

getUserListFromCSV: Process a CSV with Github, associates with LDAP and provide a list of github accounts
(Input: transformDict2CSV, output: List of github accounts)

getOrgMembership: Gets a dictionary that correlates users and membership from a list of organizations:
(input: list of github organizations, output: dictionary of users on each org)

analyzeLog: Analyze a list of log files with estructure export-*_.json and returns the logs matching users in a list)

downloadReposfromList: Download all repos from a list.

**Comment by bbelderbos** [comment]
thanks, you could make those docstrings :)

so in what order will they be called? 

maybe it would be beneficial to make a (functional) test script that runs them all in sequence to also confirm I can get this working on my end

I already see 2 dependencies we need to work around:
- github api
- ldap

can you do this so it becomes workable to a team of devs (for now just me but still haha)
