### ISSUE TITLE
github json files and ldap access or mock server

### ISSUE THREAD

**Issue by bbelderbos** [abaddonpuff/bladeART#8]
As per PR feedback opening this issue to make a reproducible environment we can both work with (and that does not involve work access)

**Comment by bbelderbos** [comment]
good work, btw did you push your last commit you did on the call to github? I don't see it here

**Comment by bbelderbos** [comment]
had some other things to do today, later tonight or tomorrow I will try out your test script and let you know ...

did you make any more progress meanwhile?

**Comment by abaddonpuff** [comment]
I realized I never pushed the code, I'm sorry. Screwed a little bit on the branches but we can discuss about that on Thursday.  When I changed the branch all the progress was gone and was not sure how to revert. But now its fixed. (I had a local copy on a different folder.)

**Comment by bbelderbos** [comment]
No way? Can you trace back what the steps were so we can troubleshoot what happened?

I did not see a PR, but I was able to see 2 new commits on the django branch:
https://github.com/abaddonpuff/bladeART/commit/24e0b392b7cc4a852edca87cb19c5972b286c8aa
https://github.com/abaddonpuff/bladeART/commit/026a9c1ea86dc4a99f45e21e4223b6e98c287b32

Which I will review in a bit. Apart from that code, any stoppers and what are the next steps?

I also need to run your test generator code yet, will do that later today ...

**Comment by bbelderbos** [comment]
test script runs fine on my end and it seems you committed some outputs already, so next steps is to integrate all this into a django view @abaddonpuff right? talk tomorrow ...

**Comment by abaddonpuff** [comment]
Correct. I'm working into figuring out the models and views for this app.

**Comment by bbelderbos** [comment]
ok any progress? well, we'll discuss in our session later
